from __future__ import annotations

import shutil
from pathlib import Path


def rm_tree(p: Path) -> None:
    if p.exists():
        shutil.rmtree(p)
        print(f"removed {p}")


def rm_pycache(root: Path) -> int:
    """Remove __pycache__ under repo source trees only (not under .venv)."""
    n = 0
    for rel in ("scripts", "tests", "tools", "skills", "docs"):
        base = root / rel
        if not base.is_dir():
            continue
        for d in sorted(base.rglob("__pycache__"), reverse=True):
            if d.is_dir():
                shutil.rmtree(d)
                n += 1
                print(f"removed {d}")
    return n


def main() -> int:
    root = Path(__file__).resolve().parents[1]

    # Regenerated by convert_review_materials.py + make_safe_md_copies.py
    rm_tree(root / "review_materials" / "_md")
    # Legacy output from convert_review_to_md.py
    rm_tree(root / "review_materials" / "converted")

    # Optional: converted docs cache (per .gitignore)
    rm_tree(root / "docs" / "_converted")

    n = rm_pycache(root)
    print(f"removed {n} __pycache__ dir(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
